config/routes.rb
HappyTao::Application.routes.draw do
  devise_for :users

  resources :deals
  root :to => "deals#index"

end

app/models/crawler_site.rb
class CrawlerSite
  include Mongoid::Document
  field :name, type: String
  field :url, type: String
end

app/models/deal.rb
class Deal
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title,   type: String
  field :price,   type: BigDecimal
  field :count,   type: Integer
  field :link,    type: String
  field :status,  type: Integer
  field :image_name, type: String
  field :image_link, type: String
  field :sort_id, type: Integer

  belongs_to :sort

  paginates_per 50

  mount_uploader :image, ImageUploader

  before_save :save_image, :gen_default_name

  def save_image
    begin
      url = open(image_link)
      self.image = MiniMagick::Image.read(url)
    rescue => e
      Rails.logger.info "=====>#{self}::#{__method__} error: #{e.inspect}"
    end
  end

  def gen_default_name
    self.image_name = File.basename(image.filename, '.*').titleize if image
  end

end

app/models/sort.rb
class Sort
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name

  has_many :deals, dependent: :destroy

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/crawler_sites_controller.rb
class CrawlerSitesController < ApplicationController
  # GET /crawler_sites
  # GET /crawler_sites.json
  def index
    @crawler_sites = CrawlerSite.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @crawler_sites }
    end
  end

  # GET /crawler_sites/1
  # GET /crawler_sites/1.json
  def show
    @crawler_site = CrawlerSite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @crawler_site }
    end
  end

  # GET /crawler_sites/new
  # GET /crawler_sites/new.json
  def new
    @crawler_site = CrawlerSite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @crawler_site }
    end
  end

  # GET /crawler_sites/1/edit
  def edit
    @crawler_site = CrawlerSite.find(params[:id])
  end

  # POST /crawler_sites
  # POST /crawler_sites.json
  def create
    @crawler_site = CrawlerSite.new(params[:crawler_site])

    respond_to do |format|
      if @crawler_site.save
        format.html { redirect_to @crawler_site, notice: 'Crawler site was successfully created.' }
        format.json { render json: @crawler_site, status: :created, location: @crawler_site }
      else
        format.html { render action: "new" }
        format.json { render json: @crawler_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crawler_sites/1
  # PUT /crawler_sites/1.json
  def update
    @crawler_site = CrawlerSite.find(params[:id])

    respond_to do |format|
      if @crawler_site.update_attributes(params[:crawler_site])
        format.html { redirect_to @crawler_site, notice: 'Crawler site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @crawler_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler_sites/1
  # DELETE /crawler_sites/1.json
  def destroy
    @crawler_site = CrawlerSite.find(params[:id])
    @crawler_site.destroy

    respond_to do |format|
      format.html { redirect_to crawler_sites_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    sort_id = params[:sort_id].blank? ? Sort.first.id : params[:sort_id]
    @deals = Deal.where(sort_id: sort_id).page(params[:page]).per(9)
  end

  def show
    @deal = Deal.find(params[:id])
  end

end

app/controllers/session_controller.rb
class SessionController < Devise::SessionsController
  #before_filter :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawler_sites_helper.rb
module CrawlerSitesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/crawler_sites/_form.html.erb
<%= form_for(@crawler_site) do |f| %>
  <% if @crawler_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crawler_site.errors.count, "error") %> prohibited this crawler_site from being saved:</h2>

      <ul>
      <% @crawler_site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crawler_sites/edit.html.erb
<h1>Editing crawler_site</h1>

<%= render 'form' %>

<%= link_to 'Show', @crawler_site %> |
<%= link_to 'Back', crawler_sites_path %>

app/views/crawler_sites/index.html.erb
<h1>Listing crawler_sites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crawler_sites.each do |crawler_site| %>
  <tr>
    <td><%= crawler_site.name %></td>
    <td><%= crawler_site.url %></td>
    <td><%= link_to 'Show', crawler_site %></td>
    <td><%= link_to 'Edit', edit_crawler_site_path(crawler_site) %></td>
    <td><%= link_to 'Destroy', crawler_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crawler site', new_crawler_site_path %>

app/views/crawler_sites/new.html.erb
<h1>New crawler_site</h1>

<%= render 'form' %>

<%= link_to 'Back', crawler_sites_path %>

app/views/crawler_sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @crawler_site.name %>
</p>

<p>
  <b>Url:</b>
  <%= @crawler_site.url %>
</p>


<%= link_to 'Edit', edit_crawler_site_path(@crawler_site) %> |
<%= link_to 'Back', crawler_sites_path %>

app/views/deals/index.html.erb
<%= render_cell :deals, :list, @deals %>
<%#= render_cell :deals, :recommended_deals %>

app/views/deals/show.html.erb
<div class="deal_cont">
  <div class="deal_cont_L">
    <%= image_tag("more_photo.jpg")%>
  </div>
  <div class="deal_cont_R">
    <div class="deal_tu" >
      <img src="<%= @deal.image_link %>" />
    </div>
    <div class="deal_p">
      <h2><a target="_blank" href="<%= @deal.link %>"><%= @deal.title %></a></h2>
      <%= image_tag("tu_3.jpg")%>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyTao</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">

  $(function(){
	  $("#img-txt-box1").imgTxtCut({
		  speed : 300
	  });
  });

  </script>
</head>
<body id="main">

<div class="navbar">
 <%= render :partial => "/share/navbar"%>
 <%= yield %>
 <%= render :partial => "/share/foot"%>
</div>
  </body>
</html>

app/views/share/_foot.html.erb
<footer>
<p>&copy; Tsinghan 2013</p>
</footer>

app/views/share/_navbar.html.erb
<div class="denglu">
  <div class="dlLeft">
    <ul>
      <li class="shouye"><a href="#">首页</a></li>
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <li><%= link_to "退出", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "登录", new_user_session_path %></li>
        <li><%= link_to "注册", new_user_registration_path %></li>
      <% end %>
      <li><a href="#">邀请好友</a></li>
    </ul>
  </div>
  <div class="dlR">
    <ul>
      <li class="shouye"><a href="#">WAP版</a></li>
      <li class="shouye"><a href="#">手机客户端</a></li>
      <li class="shouye"><a href="#">收藏</a></li>
      <li><a href="#">意见反馈</a></li>
    </ul>

  </div>
</div>
<div class="header">
  <div class="top">
    <ul>
      <li class="logo"><a href="#">LOGO</a></li>
      <li class="jingxuan"><a href="#">精选独家优惠www.happytao.com</a></li>
      <li><a href="#">手机客户端</a></li>
    </ul>
  </div>
  <div class="nav">
    <div class="nav_left">
      <ul>
        <li class="current">全部</li>
        <% Sort.all[0,10].each do |sort| %>
          <li><a href="<%= deals_path(sort_id: sort.id)%>"><%= sort.name %></a></li>
        <% end %>
      </ul>	
    </div>
    <div class="nav_right">
      <ul>
        <li><a href="#">晒单</a></li>
        <li><a href="#">幸运抽奖</a></li>
        <li><a href="#">积分兑换</a></li>
        <li><a href="#"><%= image_tag("qiandao.gif")%></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>